### ISSUE TITLE
Reduce CTA bar padding

### ISSUE THREAD

**Issue by bspeare** [uiowa/admissions-viewbook#47]
# Problem 

Many counselors are using laptops with a smaller screen size where the cta bar gets in the way of some of the data/stats that they need to share on the site.

# Proposed Solution

Reduce the amount of space the links are taking up as well as setting some vh sizing with media queries.

**Comment by bspeare** [comment]
After the discussion today, we will move forward with reducing the amount of space the links are taking up as well as setting some `vh` sizing with media queries.

**Comment by joewhitsitt** [comment]
Should this happen in components/grid-panel (UIDS) or locally in the viewbook?

**Comment by bspeare** [comment]
This can happen locally in the viewbook.

**Comment by joewhitsitt** [comment]
here we go...
